### ISSUE TITLE
Pydantic Error

### ISSUE THREAD

**Issue by owais3901** [IntelligenzaArtificiale/hugging-chat-api-LLM-custom-Wrapper#1]
Hello, Facing an error 
    generations.append([Generation(text=text)])
  File "/home/owais/anaconda3/envs/get_geek/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/home/owais/anaconda3/envs/get_geek/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

**Comment by IntelligenzaArtificiale** [comment]
Pls try to 
`pip3 install -U langchain hugchat`

**Comment by owais3901** [comment]
Fixed the issue by converting the response as str in __call__ function

Like this.

resp = str(resp)

**Comment by owais3901** [comment]
@IntelligenzaArtificiale Thanks for the response. Waiting for the support of other langchain features as well..
